### ISSUE TITLE
mstpctl and cisco switch cli commands mapping

### ISSUE THREAD

**Issue by srajeshinfotech** [mstpd/mstpd#102]
Dear Team,

Kindly map the "mstpctl and Cisco switch cli" commands and update the documents.

Best Regards,
Rajesh~
iRxTx.com
9600635770

**Comment by commodo** [comment]
Hey,

Sorry for the late reply.
I've been on vacation and forgot to reply last week when I got back; many emails piled up.

So, what do you mean about mapping the `mstpctl and Cisco switch cli` docs?
I'm a bit vague on that.

Thanks
Alex
