### ISSUE TITLE
configure option to disable -Werror

### ISSUE THREAD

**Issue by jsmolic** [mstpd/mstpd#105]
Hello, I'm trying to package mstpd for Gentoo.
Would you be able to add a configure option to disable `-Werror`? We ussually don't like to build packages with the flag as it can often break the builds, and it would be more convenient for us to have a configure switch to turn it off.

**Comment by commodo** [comment]
> Hello, I'm trying to package mstpd for Gentoo.
> Would you be able to add a configure option to disable `-Werror`? We ussually don't like to build packages with the flag as it can often break the builds, and it would be more convenient for us to have a configure switch to turn it off.

so a first question is: are you seeing any errors?

we can add a disable-errors-as-warnings;
it feels a bit funky to add a flag like this, but ok ¯\_(ツ)_/¯
do you want to spin-up a PR, or shall i?

**Comment by jsmolic** [comment]
Yes, I'm seeing
```
In function ‘strncpy’,
    inlined from ‘get_hwaddr’ at netif_utils.c:63:5:
/usr/include/bits/string_fortified.h:91:10: error: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
   91 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘get_flags’ at netif_utils.c:77:5:
/usr/include/bits/string_fortified.h:91:10: error: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
   91 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘if_shutdown’ at netif_utils.c:97:5:
/usr/include/bits/string_fortified.h:91:10: error: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
   91 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘ethtool_get_speed_duplex’ at netif_utils.c:110:5:
/usr/include/bits/string_fortified.h:91:10: error: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
   91 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.    -Os -Wall -D_REENTRANT -D__LINUX__ -I. -D_GNU_SOURCE -g3 -O0 -Werror -DMSTPD_PID_FILE='"/var/run/mstpd.pid"' -O2 -pipe -c -o mstpd-ctl_socket_server.o `test -f 'ctl_socket_server.c' || echo './'`ctl_socket_server.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.    -Os -Wall -D_REENTRANT -D__LINUX__ -I. -D_GNU_SOURCE -g3 -O0 -Werror -DMSTPD_PID_FILE='"/var/run/mstpd.pid"' -O2 -pipe -c -o mstpd-hmac_md5.o `test -f 'hmac_md5.c' || echo './'`hmac_md5.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.    -Os -Wall -D_REENTRANT -D__LINUX__ -I. -D_GNU_SOURCE -g3 -O0 -Werror -DMSTPD_PID_FILE='"/var/run/mstpd.pid"' -O2 -pipe -c -o mstpd-driver_deps.o `test -f 'driver_deps.c' || echo './'`driver_deps.c
cc1: all warnings being treated as errors
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.    -Os -Wall -D_REENTRANT -D__LINUX__ -I. -D_GNU_SOURCE -g3 -O0 -Werror -DMSTPD_PID_FILE='"/var/run/mstpd.pid"' -O2 -pipe -c -o mstpctl-ctl_main.o `test -f 'ctl_main.c' || echo './'`ctl_main.c
make[1]: *** [Makefile:672: mstpd-netif_utils.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/string.h:519,
                 from mstp.c:40:
In function ‘strncpy’,
    inlined from ‘MSTP_IN_set_mst_config_id’ at mstp.c:1617:9:
/usr/include/bits/string_fortified.h:91:10: error: ‘__builtin_strncpy’ specified bound 32 equals destination size [-Werror=stringop-truncation]
   91 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

I see that there is a `--enable-devel` option, so perhaps we can just move the `-Werror` flag behind that one instead of adding new option for `-Werror`, what do you think?

**Comment by commodo** [comment]
> I see that there is a `--enable-devel` option, so perhaps we can just move the `-Werror` flag behind that one instead of adding new option for `-Werror`, what do you think?

sorry for the late reply;
i've been thinking about it;
i've also been trying to reproduce it, but it seems that fortify-headers need a bit of custom installation;

so, let's do put -Werror under --enable-devel for now;
we can enable this flag in the CI;
maybe i need to update the CI a bit first to use github actions;

**Comment by jsmolic** [comment]
@commodo Thanks, that sounds good. Do you need a PR?

**Comment by commodo** [comment]
> @commodo Thanks, that sounds good. Do you need a PR?

yep;
i can do one these days;
or you can;

**Comment by SoapGentoo** [comment]
https://flameeyes.blog/2009/02/25/future-proof-your-code-dont-use-werror/
The fundamental problem is that you cannot predict what warnings compilers will add in the future, and this places a big strain on our infra because it blocks us from upgrading our compilers. `-Werror` is a great tool, but it only really makes sense in CI, not on users' systems.

**Comment by commodo** [comment]
Created PR:
https://github.com/mstpd/mstpd/pull/107

I tested and it seemed to work.

After this gets merged, I might do a quick release to mark this change.

**Comment by jsmolic** [comment]
> Created PR:
> #107
> 
> I tested and it seemed to work.
> 
> After this gets merged, I might do a quick release to mark this change.

Thank you, that would be helpful

**Comment by SoapGentoo** [comment]
@commodo thanks for merging our PRs, could you cut a new release today?

**Comment by commodo** [comment]
done:
https://github.com/mstpd/mstpd/releases/tag/0.0.9

thanks :)

**Comment by commodo** [comment]
will close this issue in 1 day if no objections;

**Comment by jsmolic** [comment]
@commodo Thanks, I think everything is done here so I'll close the issue.
