### ISSUE TITLE
Port priority issue with MSTP protocol

### ISSUE THREAD

**Issue by hilmarm** [mstpd/mstpd#117]
In the simplest use-case with two MSTP bridges with two connections as shown below

```
+-----------------+                               +------------------+
|                 |---------+  vid: 2   +---------|                  |
|                 | port_a  |-----------| port_c  |                  |
|     bridge_1    |+--------+           +--------++    bridge_2      |
|      mstp       |                               |     mstp         |
|                 |+--------+   vid: 2  +--------++                  |
|                 |  port_b |-----------| port_d  |                  |
|                 |+--------+           +--------+|                  |
+-----------------+                               +------------------+


```        

We use the following configuration for the left node
```
# mstpctl createtree bridge_1 2
# mstpctl setvid2fid bridge_1 2:2
# mstpctl setfid2mstid bridge_1 2:2
```
And identically on the right node
```
# mstpctl createtree bridge_2 2
# mstpctl setvid2fid bridge_2 2:2
# mstpctl setfid2mstid bridge_2 2:2
```
Listing port states in MSTID=2 on left node with ``mstpctl showtreeport`` gives the following output, showing that ``port_c`` is blocking and ``port_a`` is forwarding

```
# mstpctl showtreeport swbridge port_a 2
swbridge:port_a MSTI 2 info
  role               Root                    port id              8.001
  state              forwarding              disputed             no
  internal port cost 1000                    admin internal cost  0
  dsgn regional root 8.002.76:E8:E5:A6:0E:BB dsgn internal cost   0
  designated bridge  8.002.76:E8:E5:A6:0E:BB designated port      8.001

# mstpctl showtreeport swbridge port_c 2
swbridge:port_c MSTI 2 info
  role               Alternate               port id              8.002
  state              discarding              disputed             no
  internal port cost 1000                    admin internal cost  0
  dsgn regional root 8.002.76:E8:E5:A6:0E:BB dsgn internal cost   0
  designated bridge  8.002.76:E8:E5:A6:0E:BB designated port      8.002
```

Now we bump the priority of ``port_c`` in order to unblock it
```
# mstpctl settreeportprio bridge_1 port_c 0 2
```

However, ``port_c`` remains blocked/discarding although its priority was increased. 

Just to show that there is no issue with setting the cost, decreasing the cost with
```
# mstpctl settreeportcost swbridge port_c 2 100
```

We now see the port state changing
```
# mstpctl showtreeport swbridge port_c 2

swbridge:port_c MSTI 2 info
  role               Root                    port id              8.002
  state              forwarding              disputed             no
  internal port cost 100                     admin internal cost  100
  dsgn regional root 8.002.76:E8:E5:A6:0E:BB dsgn internal cost   0
  designated bridge  8.002.76:E8:E5:A6:0E:BB designated port      8.002
```

**Comment by commodo** [comment]
Hey,

Thanks for the detailed report.
For MSTP, it is known that it isn't perfect/working.

But nobody had time to look at it and fix/find any issues.
It's known that STP and RSTP work well.

If you want, you can try to submit some potential fixes for review.
Maybe the fix is easy to review, who knows.

I don't have time to check issues too much in depth at this point in time.

Alex

**Comment by hilmarm** [comment]
This issue was reported was due to a misunderstanding of the operations of MSTP.

The port priority calculation is done via the port priority vector, which among other contains the DesignatedBridgeID and the DesignatedPortID (i.e. port_a in our use-case), but not any other port. So only changing the priority of ports that are designated ports will impact what is blocked/forwarded.

We can close this issue.
