### ISSUE TITLE
RFE: support distributions without brctl using iproute2

### ISSUE THREAD

**Issue by sshambar** [mstpd/mstpd#123]
brctl isn't available on Centos 8 Stream (possibly others).

As brctl is critical to the functioning of the mstpd scripts (even bridge-stp when mstpd fails), it would be useful to have a fallback to iproute2 tools when it's not available:

 - brctl addbr $bridge ->  ip link add name $bridge type bridge
 - brctl delbr $bridge -> ip link del $bridge
 - brctl addif $bridge $port -> ip link set dev $port master $bridge
 - brctl delif $bridge $port -> ip link set dev $port nomaster
 - brctl stp $bridge {on|off} -> ip link set $bridge type bridge stp_state {state}

I found that all these worked even on OpenWRT with ip-tiny... perhaps it makes sense to just use ip for everything to reduce the dependencies?

I can work up a patch if that sounds right.

**Comment by commodo** [comment]
On OpenWrt, netfid usually manages bridges.
The typical workflow there, would be have netifd handle the bridges, then configure mstpd with the bridges.

That's what this init script does:
https://github.com/openwrt/packages/blob/master/net/mstpd/files/etc/init.d/mstpd.init

Well, I admit that I haven't used it on OpenWrt for a while.

But, a question: so, there is on bridge-utils anywhere in CentOS8 Stream?

**Comment by sshambar** [comment]
It was deprecated in RHEL7, and has now finally be removed in Centos 8 Stream (in anticipation of RHEL9 I'm guessing):

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.7_release_notes/deprecated_functionality

You can, of course, download the rpm src and compile it, but that's not exactly clear to the average "just dnf install" user... since /sbin/ip is required anyway, it would be simple enough to just use that and remove the brctl requirement.
