### ISSUE TITLE
bridge-stp script logger invokation incompatible with BusyBox logger

### ISSUE THREAD

**Issue by avlec** [mstpd/mstpd#134]
bridge-stp script calls logger with the full options `--tag` and `--stderr` BusyBox only supports the shorthand of the options `-t` and `-s` respectively. The shorthands should also work on non-busybox systems.

https://elixir.bootlin.com/busybox/1.35.0/source/sysklogd/logger.c
https://man7.org/linux/man-pages/man1/logger.1.html

**Comment by commodo** [comment]
[ i thought i replied already, but seems i did not hit the comment button]
sure;

feel free to spin up a patch/PR

if not, i can do that in the next few days

**Comment by commodo** [comment]
see https://github.com/mstpd/mstpd/pull/135

**Comment by commodo** [comment]
merged

thanks
