### ISSUE TITLE
MSTPD doesn't work with busybox pidof routine

### ISSUE THREAD

**Issue by colin-foster-in-advantage** [mstpd/mstpd#136]
The latest Busybox v1.35.0 contains pidof, but it doesn't support the "-c" argument. As such, every call of pidof in bridge-stp seem to fail.

I don't know the implications of dropping the "-c" but as far as I can tell, this'll brake any Buildroot systems.

The combination of removing the '-c' arguments, and moving the bridge-stp from /usr/sbin to /sbin seem to be the two tickets I needed to get mstpd up and running. I'll be looking more into the latter to see if that really is the issue.

**Comment by commodo** [comment]
From docs:  https://linux.die.net/man/8/pidof

```
-c
    Only return process ids that are running with the same root directory. This option is ignored for non-root users, as they will be unable to check the current root directory of processes they do not own. 
```

i'd say we can remove it if it helps with Busybox
the argument seems to be some sort of extra-safety mechanism for setups with many apps installed

**Comment by colin-foster-in-advantage** [comment]
If dropping it is an option, that'd help me (and anyone who uses Buildroot, from what I can tell)

I took a stab at detection as well, if keeping the -c option is necessary:

https://github.com/colin-foster-in-advantage/mstpd/tree/pidof_repair

I'm happy to make a PR for "-c" removal or "-c detection"

**Comment by commodo** [comment]
merged

thanks; 

will close this now; if there are any objections feel free to ping me or re-open
