### ISSUE TITLE
BPDU filter active but still "Configuration" BPDU messages are sent

### ISSUE THREAD

**Issue by mklntf** [mstpd/mstpd#138]
Hello,

I activated BPDU filtering on port 3 of my switch and tought that no more BDPU messages are sent out after that. But it seems my assumption is wrong. Can anyone explain what is happening and why some BPDU messages are still sent?

```
mstpctl setportbpdufilter br0 sw0p3 yes
mstpctl showportdetail br0 sw0p3 bpdu-filter-port
yes
```

The highlighted line shows the moment the bpdu-filter was activated.

![image](https://user-images.githubusercontent.com/32884828/188413812-ddc35380-bb55-42ac-9039-76d7dd2535ee.png)

I use mstpd Version 0.0.9

Thank you
Markus

**Comment by mklntf** [comment]
It turned out that these are different messages. STP is activated via `ip link set br0 type bridge stp_state 1` and MSTP is activated as well. BPDU filtering deactivates the MSTP BPDU messages as expected but the STP BPDU messages remain active. After deactivating stp via `ip link set br0 type bridge stp_state 0` no more BPDU messages are sent from this port.

**Comment by commodo** [comment]
Thanks for the message.

If this is no longer an issue I will close it.

I'm just getting back from vacation and going through my inbox.
