### ISSUE TITLE
bridge-stp <bridge> <start|stop> is not called

### ISSUE THREAD

**Issue by LookUFOwxy** [mstpd/mstpd#140]
When I use brctl stp Bridge on, I found bridge-stp <bridge> <start|stop> is not called,  I am sure that /sbin/mstpd, /sbin/mstpctl, and /sbin/bridg-stp exist and are executable

**Comment by LookUFOwxy** [comment]
also, if exec "brctl stp xxx on", then exec "bridge-stp xxx start", there will be 2 kinds of packets, config bpdu(from stp), rst bpdu(from rstp), is this normal?

**Comment by LookUFOwxy** [comment]
anyone has idea about this problem?

**Comment by PaulSD** [comment]
bridge-stp is normally called by either NetworkManager (via https://github.com/mstpd/mstpd/blob/master/utils/nm-dispatcher.in) or ifupdown (via https://github.com/mstpd/mstpd/blob/master/utils/ifupdown.sh.in ... See the comments in that file for Ubuntu or https://github.com/mstpd/mstpd/blob/master/mstpd.spec#L50 for RHEL).
