### ISSUE TITLE
Ensure the bridge STP state is set to user space

### ISSUE THREAD

**Issue by vivien** [mstpd/mstpd#17]
Second part of original issue: https://sourceforge.net/p/mstpd/discussion/general/thread/302c8299/
First part reported in #9 

[...] it might be useful to add a sanity check to make sure kernel is in the right BR_USER_STP mode:

```
cat /sys/class/net/br0/bridge/stp_state
2
```

**Comment by geek0007** [comment]
How to set this?
I found -

$echo "2" >/sys/class/net/br0/bridge/stp_state

set it to 1 and kernel stp is turned on which can be checked using brctl.

**Comment by vivien** [comment]
The STP state through sysfs (the `stp_state` file), ioctl or netlink interfaces returns the exact state on read operation (0 = disabled, 1 = kernel STP, 2 = user STP), but accepts only a boolean on write operation, e.g.:

````
# echo 42 > /sys/class/net/br0/bridge/stp_state
# cat /sys/class/net/br0/bridge/stp_state
1
````

If `/sbin/bridge-stp` is present on the file system, the kernel executes it when starting/stopping STP. When enabling STP, if this executable returns not 0, Linux uses kernel STP.

As a sanity check, it'll be only reliable to get the STP state via netlink (preferable over ioctl) and ensure the value 2.

Here's an example with a dummy `bridge-stp` file:

````
# ln -s /bin/true /sbin/bridge-stp
# echo 42 > /sys/class/net/br0/bridge/stp_state
# cat /sys/class/net/br0/bridge/stp_state
2
````

**Comment by vivien** [comment]
I've sent a patch to upstream bridge to improve a little bit the userspace STP experience:
https://git.kernel.org/cgit/linux/kernel/git/davem/net-next.git/commit/?id=3084331

Should land in Linux 4.9.

**Comment by commodo** [comment]
Looking at this issue (after this time), I think the current state of things is good enough as-is.
i.e. the kernel patch that @vivien did looks good enough to debug issues with `/sys/class/net/br0/bridge/stp_state` being 0,1,2

I don't think we should do more right now.
The initial report looks more like an idea/suggestion, that may be valid, but I don't if we should bother much more (that the kernel patch).
