### ISSUE TITLE
why outgoing BPDU source MAC is 00:00:00:00:00:00 ?

### ISSUE THREAD

**Issue by geek0007** [mstpd/mstpd#19]
I found out going configuration BPDU source MAC is empty.

Function in rstplib/transmit.c  build_bpdu_header()  call STP_OUT_get_port_mac (port_index, bpdu_packet.mac.src_mac); to generate MAC 

rstplib/stp_to.c version

```
void
STP_OUT_get_port_mac (int port_index, unsigned char *mac)
{
  static long pid = -1;
  static unsigned char mac_beg[] = {'\0', '\0', '\0', '\0', '\0', '\0'};

  if (pid < 0) {
    pid = getpid ();
    memcpy (mac_beg + 1, &pid, 4);
  }
  memcpy (mac, mac_beg, 5);
  mac[5] = port_index;
  //memcpy (mac, STP_MAIN_get_port_mac (port_index), 6);
}

```

rstplib transmit.c use stp_to.c version as per the source trace.

bridge_track.c version:

```
void /* for bridge id calculation */ STP_OUT_get_port_mac(IN int port_index,
                              OUT unsigned char
                              *mac)
{
    LOG("port index %d", port_index);
    struct ifdata *port = find_port(port_index);
    TST(port != NULL,);
    get_hwaddr(port->name, mac);
}
```

easy source browsing is here:
[https://sourceforge.net/p/rstp-linux-2016/code/ci/master/tree](url)

copy past link above, clicking don't work.

**Comment by commodo** [comment]
as far as mstpd's code is concerned, `get_hwaddr()` should fill in the correct MAC addr
not sure if we should care about rstplib, since it's not being used

**Comment by commodo** [comment]
closing this issue as unrelated ; 
the rstplib ;

there is a `get_hwaddr()` function in https://github.com/mstpd/mstpd/blob/master/netif_utils.c#L58

however that does an `iotcl()` ; if that returns 0 or err, we can't do anything here
and is not in the scope of this project
