### ISSUE TITLE
why OPenWRT CC 15.05.1 with Linux kernel 3.18.27 can not listen on ETH_P_802_2 ??

### ISSUE THREAD

**Issue by geek0007** [mstpd/mstpd#21]
mstp could not listen 802.2 STP traffic-

in packet.c --

s = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_802_2));

this line of code need to be updated to

s = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_ALL));

which is highly dangerous and I found crashes of mstpd when there is some huge traffic.

so How this can be fixed?
Is kernel network configuration is missing something or this is embedded library limitation?

**Comment by commodo** [comment]
@geek0007 
sorry for taking too long to answer on this;

to have `htons(ETH_P_802_2)` here, you'd need to build your kernel with at least `CONFIG_LLC=y` 

you could also enable `CONFIG_STP=y` ; that would also enable `CONFIG_LLC=y`
