### ISSUE TITLE
Add batch command to mstpctl

### ISSUE THREAD

**Issue by dvitas** [mstpd/mstpd#4]
There is a need to add some command which enables batch parameters setting. It can be command-line option which gives the name of the file containing list of ordinary commands.
Main goal: implement many settings in one batch. E.g. when assigning VIDs to FIDs it is too long to assign it one-by-one. We already have internal interface to set the whole mapping table in one bulk, there is only lack of user interface for the task.

**Comment by commodo** [comment]
if no objections, i'll try to implement this;

**Comment by dvitas** [comment]
Yes, sure, please go ahead, as well as with other issues, no objections :)

**Comment by julienfortin** [comment]
Hey guys @dvitas @commodo 

Any news on this? :)
I'm working on ifupdown2 (http://github.com/CumulusNetworks/ifupdown2/) and we could really use mstpctl batching capabilities!

Thanks,
Julien.

**Comment by commodo** [comment]
Hey,

No changes here.
At the moment I am swamped.
Not sure when I'll have time to allocate here.

Thanks
Alex

**Comment by commodo** [comment]
I tried a stab at implementing this myself:

https://github.com/mstpd/mstpd/commits/mstpctl-batch

Will need to make some time to test.
But if you can take a look and test them, it would also be great.

Thanks
Alex

**Comment by commodo** [comment]
PR was merged.
I've done some basic testing with and it seems to work fine.

**Comment by julienfortin** [comment]
Awesome thanks!
