### ISSUE TITLE
bpdu guard - how to clear after port blocked

### ISSUE THREAD

**Issue by ianmacpherson** [mstpd/mstpd#62]
Trying to figure out how to resolve a port after the bpdu guard has triggered.  I can't seem to find any commands to place the port back in to forwarding mode without restarting the service or reboot.

Anyone have any ideas on this?  Been digging through the code to see if there is a way around this without fully understanding the state machine.

Thanks!

**Comment by ianmacpherson** [comment]
Looks like it doesn't exist as the port is brought down with if_shutdown, but no if_bringup exists.  I was able to modify the code to clean the guard error, re-enable the port, update the state machine and bring up the port, which now works on bpdu guard disable.

**Comment by ianmacpherson** [comment]
To note.  It works, but when doing a brctl showstp br0 it shows it as still blocking, even though it is forwarding.  Haven't been able to figure out how to fix that.

**Comment by mg964** [comment]
Did anything come of the idea of an auto-bpdu-guard-recovery option?
