### ISSUE TITLE
MSTPD Max Bridges?

### ISSUE THREAD

**Issue by Platin21** [mstpd/mstpd#84]
Is there a maximum of how many bridges one can use from the mstpd daemon?

Or should it be fine that i manages up to N bridges?

**Comment by commodo** [comment]
Never tried a maximum.

I've used it up to 48 bridges a few years ago in some tests [1 bridge per port].
In theory, it could do more [up to 4094?] .

But this was with RSTP; not MSTP.

**Comment by Platin21** [comment]
Yeah i actually meant in mstp mode not rstp as there we did also run full 6 instances and had not any problems with it. 

When we use mstp with 6 vlans and all 6 bridges which each then has all 6 vlans we got some weird behaviors.

**Comment by commodo** [comment]
Apologies for the late reply here.

So, I guess the question about max-VLANS supported is answered.
I guess the issue of `When we use mstp with 6 vlans and all 6 bridges which each then has all 6 vlans we got some weird behaviors.` is a little hard to track/identify.

We know that MSTP isn't fully mature here, and that's another effort to get there.

So, will close this for now.
