### ISSUE TITLE
MSTP wrong state changes?

### ISSUE THREAD

**Issue by Platin21** [mstpd/mstpd#85]
Hello it seems the mstp does have some weird state changes in regards to the network:

So this is my current network on S2 there is the MSTP:
![mstp_4clients](https://user-images.githubusercontent.com/20503931/72317744-7e4c1400-369a-11ea-88b4-78b747903797.png)

We use it in mstp mode and it's behavior is a bit strange e.g non deterministic it almost seems.
Not only that we get a loop at the beginning but we also sometimes get one even after initial setup. 
This is quite a huge problem as this makes the stack unusable. The other thing is that we are a bit unsure why we do get such failures it seems to be related to port LANX3 which is the bridge between the two bridges we did change there the port priority just to make sure the bridges get to be the root.

And here are the state transisitons:
- Without failure:
       14:34:13 fid 11 vid 210 portState 1 2 load name: LANX4
	14:34:13 fid 11 vid 211 portState 1 2 load name: LANX4
	14:34:13 fid 11 vid 210 portState 1 3 load name: LANX4
	14:34:13 fid 11 vid 211 portState 1 3 load name: LANX4
	14:34:13 fid 10 vid 100 portState 2 2 load name: LANX3
	14:34:13 fid 10 vid 101 portState 2 2 load name: LANX3
	14:34:13 fid 10 vid 100 portState 2 3 load name: LANX3
	14:34:13 fid 10 vid 101 portState 2 3 load name: LANX3
	14:34:13 fid 11 vid 210 portState 1 1 load name: LANX4
	14:34:13 fid 11 vid 211 portState 1 1 load name: LANX4
	14:34:13 fid 11 vid 210 portState 2 2 load name: LANX3
	14:34:13 fid 11 vid 211 portState 2 2 load name: LANX3
	14:34:13 fid 11 vid 210 portState 2 3 load name: LANX3
	14:34:13 fid 11 vid 211 portState 2 3 load name: LANX3
	14:34:16 fid 10 vid 100 portState 5 2 load name: LANX7
	14:34:16 fid 10 vid 101 portState 5 2 load name: LANX7
	14:34:16 fid 10 vid 100 portState 5 3 load name: LANX7
	14:34:16 fid 10 vid 101 portState 5 3 load name: LANX7
	14:34:16 fid 11 vid 210 portState 5 2 load name: LANX7
	14:34:16 fid 11 vid 211 portState 5 2 load name: LANX7
	14:34:16 fid 11 vid 210 portState 5 3 load name: LANX7
	14:34:16 fid 11 vid 211 portState 5 3 load name: LANX7
	14:34:21 fid 11 vid 210 portState 4 2 load name: LANX1
	14:34:21 fid 11 vid 211 portState 4 2 load name: LANX1
	14:34:21 fid 11 vid 210 portState 4 3 load name: LANX1
	14:34:21 fid 11 vid 211 portState 4 3 load name: LANX1
	14:34:21 fid 10 vid 100 portState 4 2 load name: LANX1
	14:34:21 fid 10 vid 101 portState 4 2 load name: LANX1
	14:34:21 fid 10 vid 100 portState 4 3 load name: LANX1
	14:34:21 fid 10 vid 101 portState 4 3 load name: LANX1
	14:34:22 fid 10 vid 100 portState 4 1 load name: LANX1
	14:34:22 fid 10 vid 101 portState 4 1 load name: LANX1
	14:34:23 fid 11 vid 210 portState 1 2 load name: LANX4
	14:34:23 fid 11 vid 211 portState 1 2 load name: LANX4
	14:34:23 fid 11 vid 210 portState 1 1 load name: LANX4
	14:34:23 fid 11 vid 211 portState 1 1 load name: LANX4
	14:34:25 fid 11 vid 210 portState 4 1 load name: LANX1
	14:34:25 fid 11 vid 211 portState 4 1 load name: LANX1
	14:34:26 fid 10 vid 100 portState 5 1 load name: LANX7
	14:34:26 fid 10 vid 101 portState 5 1 load name: LANX7
	14:34:26 fid 11 vid 210 portState 5 1 load name: LANX7
	14:34:26 fid 11 vid 211 portState 5 1 load name: LANX7
	14:34:30 fid 10 vid 100 portState 4 2 load name: LANX1
	14:34:30 fid 10 vid 101 portState 4 2 load name: LANX1
	14:34:30 fid 10 vid 100 portState 4 3 load name: LANX1
	14:34:30 fid 10 vid 101 portState 4 3 load name: LANX1
	14:34:30 fid 11 vid 210 portState 4 2 load name: LANX1
	14:34:30 fid 11 vid 211 portState 4 2 load name: LANX1
	14:34:30 fid 11 vid 210 portState 4 3 load name: LANX1
	14:34:30 fid 11 vid 211 portState 4 3 load name: LANX1
	14:34:30 fid 10 vid 100 portState 5 2 load name: LANX7
	14:34:30 fid 10 vid 101 portState 5 2 load name: LANX7
	14:34:30 fid 10 vid 100 portState 5 3 load name: LANX7
	14:34:30 fid 10 vid 101 portState 5 3 load name: LANX7
	14:34:30 fid 11 vid 210 portState 5 2 load name: LANX7
	14:34:30 fid 11 vid 211 portState 5 2 load name: LANX7
	14:34:30 fid 11 vid 210 portState 5 3 load name: LANX7
	14:34:30 fid 11 vid 211 portState 5 3 load name: LANX7
	14:34:30 fid 10 vid 100 portState 4 1 load name: LANX1
	14:34:30 fid 10 vid 101 portState 4 1 load name: LANX1
	14:34:33 fid 10 vid 100 portState 1 2 load name: LANX4
	14:34:33 fid 10 vid 101 portState 1 2 load name: LANX4
	14:34:34 fid 10 vid 100 portState 1 3 load name: LANX4
	14:34:34 fid 10 vid 101 portState 1 3 load name: LANX4

- With failure:
       14:41:50 fid 11 vid 210 portState 1 2 load name: LANX4
	14:41:50 fid 11 vid 211 portState 1 2 load name: LANX4
	14:41:50 fid 11 vid 210 portState 1 3 load name: LANX4
	14:41:50 fid 11 vid 211 portState 1 3 load name: LANX4
	14:41:50 fid 10 vid 100 portState 2 2 load name: LANX3
	14:41:50 fid 10 vid 101 portState 2 2 load name: LANX3
	14:41:50 fid 10 vid 100 portState 2 3 load name: LANX3
	14:41:50 fid 10 vid 101 portState 2 3 load name: LANX3
	14:41:50 fid 11 vid 210 portState 1 1 load name: LANX4
	14:41:50 fid 11 vid 211 portState 1 1 load name: LANX4
	14:41:50 fid 11 vid 210 portState 2 2 load name: LANX3
	14:41:50 fid 11 vid 211 portState 2 2 load name: LANX3
	14:41:50 fid 11 vid 210 portState 2 3 load name: LANX3
	14:41:50 fid 11 vid 211 portState 2 3 load name: LANX3
	14:41:53 fid 10 vid 100 portState 5 2 load name: LANX7
	14:41:53 fid 10 vid 101 portState 5 2 load name: LANX7
	14:41:53 fid 10 vid 100 portState 5 3 load name: LANX7
	14:41:53 fid 10 vid 101 portState 5 3 load name: LANX7
	14:41:53 fid 11 vid 210 portState 5 2 load name: LANX7
	14:41:53 fid 11 vid 211 portState 5 2 load name: LANX7
	14:41:53 fid 11 vid 210 portState 5 3 load name: LANX7
	14:41:53 fid 11 vid 211 portState 5 3 load name: LANX7
	14:41:59 fid 10 vid 100 portState 5 1 load name: LANX7 // failure as the match until here
	14:41:59 fid 10 vid 101 portState 5 1 load name: LANX7
	14:41:59 fid 11 vid 210 portState 5 1 load name: LANX7
	14:41:59 fid 11 vid 211 portState 5 1 load name: LANX7
	14:42:3  fid 10 vid 100 portState 4 2 load name: LANX1
	14:42:3  fid 10 vid 101 portState 4 2 load name: LANX1
	14:42:3  fid 10 vid 100 portState 4 3 load name: LANX1
	14:42:3  fid 10 vid 101 portState 4 3 load name: LANX1
	14:42:3  fid 11 vid 210 portState 4 2 load name: LANX1
	14:42:3  fid 11 vid 211 portState 4 2 load name: LANX1
	14:42:3  fid 11 vid 210 portState 4 3 load name: LANX1
	14:42:3  fid 11 vid 211 portState 4 3 load name: LANX1
	14:42:3  fid 10 vid 100 portState 5 2 load name: LANX7
	14:42:3  fid 10 vid 101 portState 5 2 load name: LANX7
	14:42:3  fid 10 vid 100 portState 5 3 load name: LANX7
	14:42:3  fid 10 vid 101 portState 5 3 load name: LANX7
	14:42:3  fid 11 vid 210 portState 5 2 load name: LANX7
	14:42:3  fid 11 vid 211 portState 5 2 load name: LANX7
	14:42:3  fid 11 vid 210 portState 5 3 load name: LANX7
	14:42:3  fid 11 vid 211 portState 5 3 load name: LANX7
	14:42:3  fid 10 vid 100 portState 4 1 load name: LANX1
	14:42:3  fid 10 vid 101 portState 4 1 load name: LANX1
	14:42:10 fid 10 vid 100 portState 1 2 load name: LANX4
	14:42:10 fid 10 vid 101 portState 1 2 load name: LANX4
	14:42:11 fid 10 vid 100 portState 1 3 load name: LANX4
	14:42:11 fid 10 vid 101 portState 1 3 load name: LANX4
	15:9:22  fid 10 vid 100 portState 4 2 load name: LANX1
	15:9:22  fid 10 vid 101 portState 4 2 load name: LANX1
	15:9:22  fid 10 vid 100 portState 4 1 load name: LANX1
	15:9:22  fid 10 vid 101 portState 4 1 load name: LANX1

Any ideas i guess i should look at the state machine itself but i don't know if adding to much debug helpers isn't changing the Beauvoir of the entire stack.

**Comment by commodo** [comment]
> Any ideas i guess i should look at the state machine itself but i don't know if adding to much debug helpers isn't changing the Beauvoir of the entire stack.

I'm afraid that you may have to dig into the state machine yourself.
I don't have any access anymore to sufficient HW to test/check.
Well, this could be simulated via some VMs, but that also takes a bit of effort/time, and I don't have much of that either.

I know the situation isn't great.
Maybe someone else has a better handle here [than me] on this.

But, RSTP per VLAN seems to be a bit more preferred than MSTP by many people using `mstpd`.

**Comment by Platin21** [comment]
Yeah it seems like it’s related to the time when we set the link later to up it seems to work correctly.
