### ISSUE TITLE
RSTP mode: Not able to set fdelay + max age + max hops in ifcfg, but it works on command line

### ISSUE THREAD

**Issue by lagerspetz-lempea** [mstpd/mstpd#86]
Hi,

I have a ring of 32 nodes running RSTP with mstpd. Each node has one bridge with two ports, one in each direction on the ring. I want to allow the ring to recover from a break at an arbitrary location, and so I want to set maxage + maxhops to 31, (1 root + 31 hops) and fdelay must be set to 17 to allow this.

I use an ifcfg file to configure the nodes:
```
auto br0
iface br0 inet ipv4ll
    bridge_ports bridgeif0 bridgeif1
    bridge_stp on
    MSTPCTL_STP on
    MSTPCTL_PORTS bridgeif0 bridgeif1
    MSTPCTL_FDELAY 17
    MSTPCTL_MAXHOPS 31
    MSTPCTL_MAXAGE 31
```

However, when I reboot the nodes, the fdelay, maxhops, and maxage are not set but remain in defaults 15, 20 and 20. When I set the root of the network to node-1, the link towards node-1 on node-22 becomes discarding, and we have branches of 20 and 11 nodes. When I break the ring next to the root (e.g. link from node-32 back to node-1 is broken) nodes after 21 lose connectivity, because max length is less than 31.

If I SSH to the nodes and set these parameters after boot, the parameters work; like

```
ssh node-1
sudo mstpctl setfdelay br0 17
sudo mstpctl setmaxage br0 31
sudo mstpctl setmaxhops br0 31
```

and I am able to break the ring without losing connections with any nodes.
Any idea why setting parameters at boot does not work?
I have checked the output of `env` in mstpctl, and it seems to have the right `IF_MSTPCTL_*` variables.

**Comment by mg964** [comment]
The ifupdown.sh.in script looks for IF_MSTPCTL_xxx variables, have you
tried specifying the full names?

Mark

**Comment by mg964** [comment]
Actually looking at the mstpctl-utils-interfaces man page, it indicates that the syntax is:

```
      iface br0 inet static
           address 12.0.0.3
           netmask 255.255.255.0
           mstpctl_ports swp1 swp2 swp3 swp4
           mstpctl_stp on
           mstpctl_maxwait auto
           mstpctl_maxage 20
           mstpctl_fdelay 15
           mstpctl_maxhops 20
```
So try changing MSTPCTL_FDELAY to mstpctl_fdelay.

**Comment by PaulSD** [comment]
I concur, the problem is the case - the example shown in the man page works for me.

**Comment by lagerspetz-lempea** [comment]
Hi, I have solved the issue.
The problem is that the mstpctl if-pre-up.d script tries to set MAXAGE first, and only then FDELAY. The setting of MAXAGE to 31 then fails because MAXAGE must be less than (FDELAY * 2 -1).
The fix is to change the order of MAXAGE and FDELAY setting if clauses here:

https://github.com/mstpd/mstpd/blob/master/utils/ifupdown.sh.in#L110

**Comment by lagerspetz-lempea** [comment]
I realize that this will then make it diffficult to decrease fdelay when that is desired. The proper solution would probably need to check if setting fdelay is successful, and if not, try again after setting maxage. For simplicity, it could also set fdelay twice, before and after maxage.

**Comment by mg964** [comment]
Faced a similar issue with a high-level perl wrapper around mstpctl, ended up doing something like this:

age = "$IF_MSTPCTL_MAXAGE"
fwddly = "$IF_MSTPCTL_FDELAY"
currfwddly = mstpctl showbridge $IFACE fwddly

if ( 2 * ( currfwddly - 1 ) >= age )
    mstpctl setmaxage "$IFACE" age
    mstpctl setfdelay "$IFACE" fwddly
else    
    mstpctl setfdelay "$IFACE" fwddly
    mstpctl setmaxage "$IFACE" age

Essentially use the current fwddly value to determine the order in which to set the age and new fwddly.

Worth doing all this in the shell script? Depends on how good your shell script skills are...

**Comment by lagerspetz-lempea** [comment]
Yeah, that looks doable, I'll try!

**Comment by lagerspetz-lempea** [comment]
I think the script is as good as I can make it in https://github.com/mstpd/mstpd/pull/87 . Doing some testing in my environment.

**Comment by lagerspetz-lempea** [comment]
Works for me.
