### ISSUE TITLE
Missing bridge-stp

### ISSUE THREAD

**Issue by dvitas** [mstpd/mstpd#9]
Original report: https://sourceforge.net/p/mstpd/discussion/general/thread/302c8299/

Hi All,

The Makefile doesn't install bridge-stp

<pre>
-       install -m 755 bridge-stp /sbin/bridge-stp
+       install -m 755 bridge-stp $(DESTDIR)/sbin/bridge-stp
</pre>

**Comment by vivien** [comment]
Fixed by 68f238e.
