### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by chen-xiao-chen** [mstpd/mstpd#93]
Hello, first of all thank you for sharing your excellent work.
I am new to MSTP.And I plan to run it in VM.
I use "mstpctl addbridge br0" to add a bridge,
but an error "ctl_client_init: Couldn't connect to server  can't setup control connection" come.
How can I solve this problem?
Thanks.

**Comment by commodo** [comment]
Hey,

Sorry for the late reply. I was on vacation for a bit and I'm still trying to catch-up on things.
We'll probably need to create some instructions in the readme.

But you'll need to install mstpd on your machine and make sure that the `mstpd` daemon is started and runs.
Well, you should also make sure that the `/sbin/bridge-stp` script is installed.
That script can also start mstpd.
The script is generated is derived from this:
https://github.com/mstpd/mstpd/blob/master/bridge-stp.in

When that script is running, just creating bridges should via br-utils should be sufficient.

**Comment by chen-xiao-chen** [comment]
Hi,
Thanks a lot.
I can run it now.

**Comment by chen-xiao-chen** [comment]
Hi,
Thanks a lot,I can run it now.
